### ISSUE TITLE
Make serialize_into and deserialize_from public

### ISSUE THREAD

**Issue by hadronzoo** [ClickHouse/clickhouse-rs#127]
The [serialize_into](https://github.com/ClickHouse/clickhouse-rs/blob/950533f71ac83c470fef72b92c4676ab77d1e7c0/src/rowbinary/ser.rs#L10) and [deserialize_from](https://github.com/ClickHouse/clickhouse-rs/blob/950533f71ac83c470fef72b92c4676ab77d1e7c0/src/rowbinary/de.rs#L12) functions have value beyond this library. They enable writing rows to Kafka in `RowBinary` format for asynchronous inserts, allowing low-latency, durable writes without compromising throughput. This approach lets ClickHouse construct large batch inserts from Kafka. Please consider making these functions public to support this use case.

**Comment by loyd** [comment]
I'm not ready to expose these functions from this specific library because they are specific for internal usage, e.g.
```rust
pub(crate) fn deserialize_from<'de, T: Deserialize<'de>>(
    input: impl Buf,
    temp_buf: &'de mut [u8],
) -> Result<T> {
```
accepts `temp_buf` to support zero-copy borrowing cursors and it's implementation details.

Secondly, `RowBinary` can be replaced with `RowBinaryWithNamesAndTypes` (https://github.com/ClickHouse/clickhouse-rs/issues/10) in the future with a different implementation. Or, more likely with the `Native` format.

So, we can talk about taking out the implementation to another crate with notice that it _will_ become unmaintainable eventually. But it shouldn't be exposed outside of this crate because it will be broken someday, and I want to avoid introducing avoidable breaking changes.

---
It relates to https://github.com/ClickHouse/clickhouse-rs/issues/67

**Comment by hadronzoo** [comment]
That makes sense. Hopefully the Native format can be exposed as a separate crate. Thank you for considering this.
